import httpx
import json
import logging
from typing import List, Dict, Any
from app.core.config import settings
from app.schemas.schemas import AIAnalysisResponse

logger = logging.getLogger(__name__)

def analyze_symptoms(symptoms_text: str, age: int = None, gender: str = None) -> AIAnalysisResponse:
    # 1. Attempt Gemini LLM analysis if API Key is configured
    if settings.GEMINI_API_KEY:
        try:
            url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key={settings.GEMINI_API_KEY}"
            
            prompt = (
                f"You are an expert clinical medical AI diagnostic assistant.\n"
                f"Analyze the following patient presentation:\n"
                f"- Symptoms: \"{symptoms_text}\"\n"
                f"- Age: {age if age is not None else 'Unspecified'}\n"
                f"- Gender: {gender if gender is not None else 'Unspecified'}\n\n"
                f"Provide a structured JSON output matching this schema exactly:\n"
                f"{{\n"
                f"  \"possible_conditions\": [\n"
                f"    {{\n"
                f"      \"condition\": \"Condition Name\",\n"
                f"      \"probability\": 0.85,\n"
                f"      \"details\": \"Detailed description of the condition, pathophysiology relation, and diagnostic indicators.\"\n"
                f"    }}\n"
                f"  ],\n"
                f"  \"recommendations\": [\n"
                f"    \"Immediate clinical step 1\",\n"
                f"    \"Step 2\"\n"
                f"  ],\n"
                f"  \"urgency_level\": \"Low\" | \"Medium\" | \"High\" | \"Emergency\",\n"
                f"  \"disclaimer\": \"A standard clinical disclaimer.\"\n"
                f"}}\n\n"
                f"Respond ONLY with valid JSON. Do not include markdown code block syntax (like ```json ... ```)."
            )

            payload = {
                "contents": [
                    {
                        "parts": [
                            {"text": prompt}
                        ]
                    }
                ],
                "generationConfig": {
                    "responseMimeType": "application/json"
                }
            }

            # Set timeout to prevent blocking indefinitely
            response = httpx.post(url, json=payload, timeout=8.0)
            if response.status_code == 200:
                resp_json = response.json()
                raw_text = resp_json["candidates"][0]["content"]["parts"][0]["text"].strip()
                
                # Double safety parse
                data = json.loads(raw_text)
                
                # Map fields to match Pydantic schema correctly
                return AIAnalysisResponse(
                    possible_conditions=data.get("possible_conditions", []),
                    recommendations=data.get("recommendations", []),
                    urgency_level=data.get("urgency_level", "Low"),
                    disclaimer=data.get("disclaimer", "DISCLAIMER: Generated by AI.")
                )
            else:
                logger.error(f"Gemini API returned status code {response.status_code}: {response.text}")
        except Exception as e:
            logger.error(f"Failed to query Gemini API. Falling back to rules engine. Error: {e}")

    # 2. Fallback Rules-Based System (runs offline or when API fails)
    logger.info("Executing rules-based symptom analysis fallback...")
    
    text = symptoms_text.lower()
    conditions = []
    recommendations = []
    urgency = "Low"

    # Smarter token and phrase matching helpers
    has_chest = "chest" in text
    has_pain = any(k in text for k in ["pain", "hurt", "tightness", "pressure", "ache", "sharp", "discomfort"])
    has_blood = any(k in text for k in ["blood", "bleed", "bleeding", "hemorrhage", "red"])
    has_ear_head = any(k in text for k in ["ear", "ears", "head", "skull", "brain", "hearing"])

    # 1. Cardiorespiratory Distress / Chest Pain Check (Emergency)
    if (has_chest and has_pain) or any(k in text for k in ["breathing", "shortness of breath", "breath", "suffocat", "chok"]):
        conditions.append({
            "condition": "Acute Cardiorespiratory Distress / Angina",
            "probability": 0.85,
            "details": "Potential myocardial infarction (heart attack), respiratory obstruction, or lung embolism. Requires immediate emergency medical care."
        })
        recommendations.append("Call emergency services (like 108 or 911) immediately.")
        recommendations.append("Rest in a seated position. Do not engage in physical activity.")
        urgency = "Emergency"

    # 2. Bleeding from Ears / Head Injury (Emergency)
    if has_blood and has_ear_head:
        conditions.append({
            "condition": "Traumatic Head Injury / Otorrhagia (Eardrum Bleeding)",
            "probability": 0.80,
            "details": "Bleeding from the ear canal or head trauma indicating potential eardrum rupture, middle ear injury, or base of skull fracture."
        })
        recommendations.append("Seek immediate emergency medical examination at the nearest hospital.")
        recommendations.append("Do not plug the ears or block the bleeding. Keep your head slightly elevated.")
        urgency = "Emergency"

    # 3. Fever & Respiratory Infection
    if any(k in text for k in ["fever", "cough", "throat", "shivering", "chills", "cold", "flu"]):
        if any(k in text for k in ["severe", "persist", "blood", "pneumonia"]):
            conditions.append({
                "condition": "Severe Respiratory Infection (Bronchitis / Pneumonia)",
                "probability": 0.70,
                "details": "Persistent high fever and severe cough indicating deep lower respiratory track infection."
            })
            recommendations.append("Schedule a consult with a doctor within 24 hours.")
            recommendations.append("Stay hydrated and monitor body temperature regularly.")
            if urgency != "Emergency":
                urgency = "High"
        else:
            if not conditions: # only add if not already in emergency
                conditions.append({
                    "condition": "Viral Upper Respiratory Infection (Common Cold / Flu)",
                    "probability": 0.85,
                    "details": "Typical presentation of viral flu or common cold. Self-limiting in most cases."
                })
                recommendations.append("Get plenty of rest and drink warm fluids.")
                recommendations.append("Over-the-counter fever reducers or throat lozenges can help relieve symptoms.")
                if urgency not in ["Emergency", "High"]:
                    urgency = "Low"

    # 4. Gastrointestinal Check
    if any(k in text for k in ["stomach", "vomit", "diarrhea", "nausea", "belly", "abdomen", "gastric"]):
        if any(k in text for k in ["blood", "severe pain", "sharp pain", "intense"]):
            conditions.append({
                "condition": "Acute Abdomen / Gastrointestinal Bleeding",
                "probability": 0.65,
                "details": "Severe localized abdominal pain or blood in vomit/stool warrants immediate diagnostic imaging."
            })
            recommendations.append("Seek emergency medical examination to rule out appendicitis or internal bleeding.")
            if urgency != "Emergency":
                urgency = "High"
        else:
            if not conditions:
                conditions.append({
                    "condition": "Gastroenteritis / Food Poisoning",
                    "probability": 0.75,
                    "details": "Inflammation of the stomach and intestines, likely due to a viral or bacterial infection."
                })
                recommendations.append("Prioritize electrolyte replacement solutions to prevent dehydration.")
                recommendations.append("Eat a bland diet as tolerated.")
                if urgency not in ["Emergency", "High"]:
                    urgency = "Low"

    # 5. Headaches (if not matching head injury)
    if any(k in text for k in ["headache", "migraine", "temple", "migran"]):
        if not has_blood:
            conditions.append({
                "condition": "Tension Headache or Migraine",
                "probability": 0.80,
                "details": "A primary headache disorder characterized by recurrent moderate to severe pain."
            })
            recommendations.append("Rest in a quiet, dark room.")
            recommendations.append("Apply a cool compress to your forehead or temples.")
            if urgency not in ["Emergency", "High"]:
                urgency = "Low"

    # 6. Skin rashes
    if any(k in text for k in ["rash", "itch", "skin", "hives", "dermatitis"]):
        conditions.append({
            "condition": "Allergic Dermatitis / Contact Rash",
            "probability": 0.70,
            "details": "Inflammatory skin condition triggered by exposure to an allergen or irritant."
        })
        recommendations.append("Avoid scratching the affected area to prevent secondary infection.")
        recommendations.append("Apply a mild moisturizer or topical hydrocortisone.")
        if urgency not in ["Emergency", "High"]:
            urgency = "Low"

    # 7. Default if no matches found
    if not conditions:
        conditions.append({
            "condition": "Undetermined Mild Malaise",
            "probability": 0.50,
            "details": "Symptoms are broad. Further consultation is recommended to identify the underlying cause."
        })
        recommendations.append("Consult a doctor for a thorough examination.")
        recommendations.append("Keep a log of symptoms, noting what makes them better or worse.")
        urgency = "Low"

    if not recommendations:
        recommendations = ["Monitor your symptoms over the next 24-48 hours.", "Consult a healthcare provider if symptoms persist or worsen."]

    disclaimer = "DISCLAIMER: This analysis is generated by an AI assistant for informational purposes only. It is NOT a substitute for professional medical advice, diagnosis, or treatment. Always consult with a qualified physician."

    return AIAnalysisResponse(
        possible_conditions=conditions,
        recommendations=recommendations,
        urgency_level=urgency,
        disclaimer=disclaimer
    )
